version: '3.9'

services:

  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nicog
      POSTGRES_PASSWORD: Yh6NFWCEvU2*a
      POSTGRES_DB: carta_digital
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local

volumes:
  postgres-data:
    driver: local

networks:
  local:
    driver: bridge